In [1]:
import pandas as pd

In [40]:
snr=pd.read_csv("csvfiles/names.csv",index_col="email")
snr.head()

                          first            last
email
john-doe@bogusemail.com    John             Doe
maryjacobs@bogusemail.com  Mary  Smith-Robinson
davesmith@bogusemail.com   Dave           Smith
janestuart@bogusemail.com  Jane          Stuart
tomwright@bogusemail.com    Tom          Wright

In [36]:
snr[:10]

                               first            last
email
john-doe@bogusemail.com         John             Doe
maryjacobs@bogusemail.com       Mary  Smith-Robinson
davesmith@bogusemail.com        Dave           Smith
janestuart@bogusemail.com       Jane          Stuart
tomwright@bogusemail.com         Tom          Wright
steverobinson@bogusemail.com   Steve        Robinson
nicolejacobs@bogusemail.com   Nicole          Jacobs
janewright@bogusemail.com       Jane          Wright
janedoe@bogusemail.com          Jane             Doe
kurtwright@bogusemail.com       Kurt          Wright

In [37]:
snr[-1:-10:-1]

                               first       last
email
travisarnold@bogusemail.com   Travis     Arnold
johnrobinson@bogusemail.com     John   Robinson
travisarnold@bogusemail.com   Travis     Arnold
janestuart@bogusemail.com       Jane     Stuart
marypatterson@bogusemail.com    Mary  Patterson
coreysmith@bogusemail.com      Corey      Smith
coreywilks@bogusemail.com      Corey      Wilks
neilsmith@bogusemail.com        Neil      Smith
johnjacobs@bogusemail.com       John     Jacobs

In [41]:
snr['tomwright@bogusemail.com':]

                                 first       last
email
tomwright@bogusemail.com           Tom     Wright
steverobinson@bogusemail.com     Steve   Robinson
nicolejacobs@bogusemail.com     Nicole     Jacobs
janewright@bogusemail.com         Jane     Wright
janedoe@bogusemail.com            Jane        Doe
kurtwright@bogusemail.com         Kurt     Wright
kurtrobinson@bogusemail.com       Kurt   Robinson
janejenkins@bogusemail.com        Jane    Jenkins
neilrobinson@bogusemail.com       Neil   Robinson
tompatterson@bogusemail.com        Tom  Patterson
samjenkins@bogusemail.com          Sam    Jenkins
stevestuart@bogusemail.com       Steve     Stuart
maggiepatterson@bogusemail.com  Maggie  Patterson
maggiestuart@bogusemail.com     Maggie     Stuart
janedoe@bogusemail.com            Jane        Doe
stevepatterson@bogusemail.com    Steve  Patterson
davesmith@bogusemail.com          Dave      Smith
samwilks@bogusemail.com            Sam      Wilks
kurtjefferson@bogusemail.com      Kurt  Jefferson
samstuart@bogusemail.com           Sam     Stuart
janestuart@bogusemail.com         Jane     Stuart
davedavis@bogusemail.com          Dave      Davis
sampatterson@bogusemail.com        Sam  Patterson
tomjefferson@bogusemail.com        Tom  Jefferson
janestuart@bogusemail.com         Jane     Stuart
maggiejefferson@bogusemail.com  Maggie  Jefferson
marywilks@bogusemail.com          Mary      Wilks
neilpatterson@bogusemail.com      Neil  Patterson
coreydavis@bogusemail.com        Corey      Davis
stevejacobs@bogusemail.com       Steve     Jacobs
janejenkins@bogusemail.com        Jane    Jenkins
johnjacobs@bogusemail.com         John     Jacobs
neilsmith@bogusemail.com          Neil      Smith
coreywilks@bogusemail.com        Corey      Wilks
coreysmith@bogusemail.com        Corey      Smith
marypatterson@bogusemail.com      Mary  Patterson
janestuart@bogusemail.com         Jane     Stuart
travisarnold@bogusemail.com     Travis     Arnold
johnrobinson@bogusemail.com       John   Robinson
travisarnold@bogusemail.com     Travis     Arnold

In [52]:
#get method
snr.get(key=['janedoe@bogusemail.com'])

None

In [55]:
len(snr)

44

In [57]:
snr.count()

first    44
last     44
dtype: int64